version: 2.1

jobs:
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: smoke test server
          command: |
            if curl -s --head "https://google.com" 
            then
              echo "It worked!"
            else
              echo "It failed"
            fi

workflows:
  myWorkflow:
    jobs:
      - smoke_test
