version: 2.1

jobs:
  configure_infra:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - add_ssh_keys:
          fingerprints:
            - "93:0f:c3:3c:ad:f9:dc:19:1b:72:73:d9:ae:bb:a7:e6"
      - checkout
      - run:
          name: Install dependencies
          command: |
            apk add --update ansible # install the dependencies needed for your playbook
      - run:
          name: configure server
          command: |
            cd remote_control
            ansible-playbook main-remote.yml -i inventory
  smoke_test:
    docker:
      - image: alpine:latest
    steps:
      - run:
          name: smoke test server
          command: |
            if curl -s --head "https://google.com" 
            then
              echo "It worked!"
            else
              echo "It failed"
            fi

workflows:
  myWorkflow:
    jobs:
      - configure_infra
      - smoke_test
