version: 2.1

commands:
  destroy_environment:
    steps:
      - run:
          name: Destroy env
          command: |
            aws cloudformation delete-stack --stack-name my-stack

jobs:
  create_infrastructure:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Create the infra
          command: |
            aws cloudformation deploy \
              --template-file template.yaml \
              --stack-name my-stack
      - run:
          command: return 1

      - destroy_environment:
          when: on_fail
        

workflows:
  myWorkflow:
    jobs:
      - create_infrastructure
